language: go

go:
  - 1.15.x
  - 1.16.x
  - tip

matrix:
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

go_import_path: github.com/vmihailenco/treemux

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go
    env GOPATH)/bin v1.21.0
