name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          body:
            Check [CHANGELOG.md](https://github.com/uptrace/treemux/blob/master/CHANGELOG.md) for
            details
